### ISSUE TITLE
Segfault on newer Linux Distributions

### ISSUE THREAD

**Issue by manuelstengelberger** [Elytherion/tdeheroes#227] opened 2019-01-21 12:33 UTC
On newer Linux distributions you get a segfault when trying to start Optolyth. I currently use Fedora 29, but got this error also on the latest Ubuntu release. It seems to be related to https://github.com/electron/electron/issues/13972 or https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1790966 where electron has problems with glibc >= 2.28.

It seems there is a patch / workaround available which needs Optolyth to be rebuilt.

EDIT: Another possible solution would be to provide a flatpak package with the required glibc version

**Comment by Elytherion** [comment] 2019-01-21 14:37
I have no experience using Linux but if this is fixed in Electron it should work with the next update as it is going to use Electron >= 4.0.0. I won’t close the issue so you can confirm if it’s fixed.

**Comment by qw3ry** [comment] 2019-03-04 16:59
I cannot reproduce this on ArchLinux, glibc 2.28.5.
Maybe this is not glibc related?

**Comment by Koltak** [comment] 2019-03-12 10:06
Can confirm for Ubuntu 18.10.  
Seems, ArchLinux has implemented a [workaround](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/glibc&id=f2aaaac68876f6959c62ea09dcdda5d441bf4ff7) due to the seriousness of this issue.

@Elytherion can you provide a new package built with a more recent patch version of Electron? Seems like [1.1](https://github.com/Elytherion/tdeheroes/milestone/3) is still some time away.

**Comment by Elytherion** [comment] 2019-03-12 15:04
@Koltak Yeah, I think I have to. I'll try to have an update available today.

**Closed** 2019-03-13 02:16 UTC
Labels: bug, important, linux

**Comment by Elytherion** [comment] 2019-03-13 13:15
If everything works fine there will be an update available tonight.

**Comment by manuelstengelberger** [comment] 2019-03-18 18:14
Where can I download v1.0.3?

**Comment by Elytherion** [comment] 2019-03-18 19:56
I haven’t had the macOS build ready and I want to upload all builds at once to the Scriptorium. As I wasn’t home the last days—but I will be tonight—I will upload all builds for all OS‘s once I’m back.

**Comment by Elytherion** [comment] 2019-03-19 03:17
It's now available via the Scriptorium (and on the other OS's are auto-updates available as well).

**Comment by Koltak** [comment] 2019-03-19 09:16
Tested on Ubuntu 18.10: App starts and I can create characters. Thanks!

**Comment by manuelstengelberger** [comment] 2019-03-19 13:18
Runs like a charme on Fedora 29 :) Thanks!
