### ISSUE TITLE
PA bonus not correctly saved in JSON

### ISSUE THREAD

**Issue by Turakar** [Elytherion/tdeheroes#63] opened 2017-09-14 09:19 UTC
If I add a Thorwalerschild to my hero and do not change the default values, I see the correct bonuses of -5/+2 for AT/PA. In the exported JSON however AT is set to -5 and PA to -5.

**Comment by Elytherion** [comment] 2017-09-14 11:25
Actually, this wil not lead to a bug. I assume you locked the item. In this case the values used in the app will be the ones from the template. If you unlock the item, the template values are merged with the actual item object, overriding all values saved (except for amount and "Carried where").
I will look into that, it's definitely a bug. But for now you might have to stay with locked items! ;)

**Comment by Turakar** [comment] 2017-09-14 14:43
You're right, the item is locked. Thank you for having a look at this.

**Comment by Elytherion** [comment] 2017-10-08 16:18
Did you try to unlock the item, save the item and look into the JSON file again to check if PA is still -5?

**Comment by Turakar** [comment] 2017-11-03 13:58
Sorry for the delay, but I've just confirmed that this does not solve the problem as the PA modifier is still -5 after this.

**Comment by Elytherion** [comment] 2017-11-03 18:27
I still do not really understand what the problem is with my code. But of course you always have to save the changes including unlocking/locking. This is not a full fix, true.

**Comment by Elytherion** [comment] 2017-11-06 14:14
I still can't reproduce the error. Does this problem only exist with locked items? In this case it is not a bug, as the app will get (most of) the values from the saved templates. Which means you can enter `pa: 10000` but the app will still display `pa: 2`.

**Comment by Elytherion** [comment] 2017-11-09 19:22
I created a function that will delete the unecessary properties of locked items. If items are unlocked all properties will be saved. I checked saving the PA value again but it is fine. I will close this issue for now; if you still get errors with the next page, feel free to reopen this issue! 😃

**Closed by Elytherion** 2017-11-09 19:22 UTC
Labels: bug
